// Ported 1:1 from Bakerly/Bakerly/Bakeri/Models/IngredientDensity.swift.

class IngredientDensity {
  String id;
  String name;
  /// Grams per 1 US cup.
  double gramsPerCup;
  /// User-created vs. built-in seed data.
  bool isCustom;
  DateTime updatedAt;

  IngredientDensity({
    required this.id,
    required this.name,
    required this.gramsPerCup,
    this.isCustom = false,
    DateTime? updatedAt,
  }) : updatedAt = updatedAt ?? DateTime.now();

  void touch() => updatedAt = DateTime.now();

  // MARK: Derived conversions

  double get gramsPerTablespoon => gramsPerCup / 16.0;
  double get gramsPerTeaspoon => gramsPerCup / 48.0;
  double get gramsPerMilliliter => gramsPerCup / 236.588;

  // MARK: Seed data

  /// Bump this number whenever seedData changes — triggers a re-seed on next launch.
  static const int seedVersion = 6;

  static const List<(String, double)> seedData = [
    // --- Flours (wheat) ---
    ('All-Purpose Flour', 120),
    ('Bread Flour', 120),
    ('Cake Flour', 100),
    ('Unbleached Cake Flour', 120),
    ('Self-Rising Flour', 113),
    ('Whole Wheat Flour', 113),
    ('Whole Wheat Pastry Flour', 96),
    ('Pastry Flour', 106),
    ('Pastry Flour Blend', 113),
    ('High-Gluten Flour', 120),
    ('First Clear Flour', 106),
    ('Durum Flour', 124),
    ('Semolina Flour', 163),
    ('Sprouted Wheat Flour', 113),
    ('Golden Wheat Flour', 113),
    ('French-Style Flour', 120),
    ('Italian-Style Flour', 106),
    ('Irish-Style Flour', 110),
    ('Climate Blend Flour', 115),
    ('Artisan Bread Flour', 120),
    ("'00' Pizza Flour", 116),
    // --- Flours (specialty) ---
    ('Almond Flour', 96),
    ('Almond Meal', 84),
    ('Toasted Almond Flour', 96),
    ('Hazelnut Flour', 89),
    ('Coconut Flour', 128),
    ('Oat Flour', 92),
    ('Chickpea Flour', 85),
    ('Barley Flour', 85),
    ('Buckwheat Flour', 120),
    ('Rye Flour', 106),
    ('Medium Rye Flour', 106),
    ('White Rye Flour', 106),
    ('Pumpernickel Flour', 106),
    ('Rye Flour Blend', 106),
    ('Spelt Flour', 99),
    ('Teff Flour', 135),
    ('Sorghum Flour', 138),
    ('Amaranth Flour', 103),
    ('Quinoa Flour', 110),
    ('Millet Flour', 206),
    ('Brown Rice Flour', 128),
    ('Rice Flour', 142),
    ('Glutinous Rice Flour', 120),
    ('Tapioca Flour', 113),
    ('Tapioca Starch', 113),
    ('Potato Starch', 152),
    ('Potato Flour', 184),
    ('Corn Flour', 112),
    ('Cornstarch', 112),
    ('Soy Flour', 140),
    ('Masa Harina', 93),
    ('Paleo Baking Flour', 104),
    ('Keto Wheat Flour', 120),
    // --- Gluten-free flours ---
    ('Gluten-Free All-Purpose Flour', 156),
    ('Gluten-Free Bread Flour', 120),
    ('Gluten-Free Pizza Flour', 100),
    ('Gluten-Free Measure for Measure Flour', 120),
    ('Gluten-Free All-Purpose Baking Mix', 120),
    // --- Baking mixes ---
    ('All-Purpose Baking Mix', 120),
    ('Buttermilk Biscuit Flour Blend', 110),
    ('Pizza Flour Blend', 124),
    // --- Leaveners ---
    ('Baking Powder', 192),
    ('Baking Soda', 288),
    // --- Sugars & Sweeteners ---
    ('Granulated Sugar', 198),
    ('Brown Sugar', 190),
    ('Brown Sugar (packed)', 213),
    ('Dark Brown Sugar (packed)', 213),
    ('Sanding Sugar', 200),
    ('Confectioners Sugar', 113),
    ('Powdered Sugar', 113),
    ('Demerara Sugar', 220),
    ('Turbinado Sugar', 180),
    ('Coconut Sugar', 154),
    ('Maple Sugar', 156),
    ("Baker's Special Sugar", 190),
    ('Baking Sugar Alternative', 170),
    ('Cinnamon-Sugar', 200),
    ('Honey', 336),
    ('Maple Syrup', 312),
    ('Molasses', 340),
    ('Agave Syrup', 336),
    ('Corn Syrup', 312),
    ('Barley Malt Syrup', 336),
    ('Malt Syrup', 344),
    ('Boiled Cider', 340),
    ('Sweetened Condensed Milk', 312),
    ('Sweetened Condensed Coconut Milk', 288),
    // --- Fats & Oils ---
    ('Butter', 226),
    ('Butter (melted)', 226),
    ('Salted Butter', 226),
    ('Unsalted Butter', 226),
    ('Ghee', 176),
    ('Lard', 226),
    ('Vegetable Oil', 198),
    ('Olive Oil', 200),
    ('Coconut Oil', 226),
    ('Vegetable Shortening', 184),
    ('Palm Shortening', 180),
    ('Mayonnaise', 226),
    ('Peanut Butter', 270),
    ('Almond Butter', 272),
    ('Nutella', 298),
    ('Hazelnut Spread', 320),
    ('Cookie Butter', 288),
    ('Tahini', 256),
    ('Pistachio Paste', 312),
    ('Hazelnut Praline Paste', 312),
    // --- Dairy & Eggs ---
    ('Egg', 243),
    ('Egg White', 243),
    ('Egg Yolk', 243),
    ('Milk', 227),
    ('Whole Milk', 227),
    ('Buttermilk', 227),
    ('Heavy Cream', 227),
    ('Whipping Cream', 227),
    ('Half and Half', 227),
    ('Sour Cream', 227),
    ('Cream Cheese', 227),
    ('Ricotta Cheese', 227),
    ('Mascarpone Cheese', 227),
    ('Yogurt', 227),
    ('Crème Fraîche', 226),
    ('Cottage Cheese', 226),
    ('Milk Evaporated', 226),
    ('Coconut Milk', 241),
    ('Coconut Cream', 284),
    ('Cream of Coconut', 284),
    ('Buttermilk Powder', 144),
    ('Dried Nonfat Milk', 112),
    ('Dried Whole Milk', 100),
    ('Coconut Milk Powder', 114),
    // --- Chocolate & Cocoa ---
    ('Cocoa Powder', 84),
    ('Unsweetened Cocoa', 84),
    ('Chocolate Chips', 170),
    ('Dark Chocolate Chips', 170),
    ('Mini Chocolate Chips', 177),
    ('White Chocolate Chips', 170),
    ('Butterscotch Chips', 170),
    ('Chocolate Chunks', 170),
    ('Dark Chocolate (chopped)', 170),
    ('Chopped Chocolate', 170),
    ('Chocolate Syrup', 312),
    ('Cacao Nibs', 120),
    // --- Oats & Grains ---
    ('Rolled Oats', 89),
    ('Quick Oats', 89),
    ('Old-Fashioned Oats', 89),
    ('Steel Cut Oats', 140),
    ('Oat Bran', 106),
    ('Barley Flakes', 92),
    ('Barley (pearled)', 213),
    ('Barley (cooked)', 215),
    ('Rye Flakes', 124),
    ('Rye Chops', 120),
    ('Bulgur', 152),
    ('Buckwheat (whole)', 170),
    ('Millet (whole)', 206),
    ('Quinoa (whole)', 177),
    ('Quinoa (cooked)', 184),
    ('Brown Rice (cooked)', 170),
    ('White Rice (dry)', 198),
    ('Cornmeal', 138),
    ('Cornmeal (fine)', 156),
    ('Polenta', 163),
    ('Bran Cereal', 60),
    ('Wheat Berries', 184),
    ('Wheat Bran', 64),
    ('Wheat Germ', 112),
    ('Cracked Wheat', 149),
    ('Malted Wheat Flakes', 128),
    // --- Nuts & Seeds ---
    ('Almonds (whole)', 142),
    ('Almonds (sliced)', 86),
    ('Almonds (slivered)', 114),
    ('Cashews (whole)', 113),
    ('Cashews (chopped)', 113),
    ('Walnuts (whole)', 128),
    ('Walnuts (chopped)', 113),
    ('Pecans (whole)', 105),
    ('Pecans (diced)', 114),
    ('Pecan Meal', 80),
    ('Hazelnuts (whole)', 142),
    ('Macadamia Nuts', 149),
    ('Peanuts', 142),
    ('Pine Nuts', 142),
    ('Pistachios (shelled)', 120),
    ('Sunflower Seeds', 140),
    ('Pumpkin Seeds', 160),
    ('Poppy Seeds', 144),
    ('Sesame Seeds', 142),
    ('Flaxseed', 140),
    ('Flax Meal', 100),
    ('Chia Seeds', 148),
    ('Caraway Seeds', 144),
    // --- Dried Fruit ---
    ('Raisins', 149),
    ('Golden Raisins (packed)', 170),
    ('Dried Cranberries', 114),
    ('Dried Blueberries', 156),
    ('Dried Cherries', 142),
    ('Dried Apricots (diced)', 128),
    ('Dried Figs (chopped)', 149),
    ('Dates (chopped)', 149),
    ('Dried Pineapple', 142),
    ('Currants', 142),
    ('Dried Apples (diced)', 85),
    // --- Fresh Fruit ---
    ('Applesauce', 255),
    ('Bananas (mashed)', 227),
    ('Blueberries (fresh)', 155),
    ('Blueberries (frozen)', 155),
    ('Raspberries (fresh)', 120),
    ('Strawberries (sliced)', 167),
    ('Cherries (fresh, pitted)', 160),
    ('Cherries (frozen)', 113),
    ('Apples (peeled, sliced)', 113),
    ('Peaches (diced)', 170),
    ('Pears (diced)', 163),
    ('Pineapple (fresh, diced)', 170),
    ('Pineapple (crushed, drained)', 256),
    ('Rhubarb (sliced)', 130),
    ('Zucchini (shredded)', 136),
    ('Strawberries (fresh, sliced)', 167),
    // --- Vegetables ---
    ('Carrots (diced)', 142),
    ('Carrots (grated)', 99),
    ('Carrots (puréed)', 256),
    ('Onions (diced)', 142),
    ('Bell Peppers', 142),
    ('Celery (diced)', 142),
    ('Leeks (diced)', 92),
    ('Scallions (sliced)', 64),
    ('Shallots (sliced)', 156),
    ('Mushrooms (sliced)', 78),
    ('Corn (fresh)', 152),
    ('Olives (sliced)', 142),
    ('Garlic (minced)', 224),
    ('Garlic (sliced)', 149),
    ('Ginger (fresh, sliced)', 228),
    ('Pumpkin Purée', 227),
    ('Mashed Potatoes', 213),
    ('Mashed Sweet Potatoes', 240),
    ('Passion Fruit Purée', 180),
    // --- Cheese ---
    ('Cheddar Cheese (grated)', 113),
    ('Mozzarella (grated)', 113),
    ('Parmesan (grated)', 100),
    ('Feta Cheese', 114),
    ('Queso Fresco', 114),
    // --- Spreads & Sauces ---
    ('Jam', 340),
    ('Preserves', 340),
    ('Caramel Sauce', 312),
    ('Tomato Paste', 232),
    ('Pizza Sauce', 228),
    ('Lemon Curd', 226),
    ('Basil Pesto', 224),
    ('Guava Paste', 400),
    ('Marshmallow Fluff', 128),
    ('Almond Paste', 259),
    ('Marzipan', 290),
    // --- Liquids ---
    ('Water', 227),
    ('Coffee', 227),
    ('Espresso', 227),
    ('Apple Juice', 250),
    ('Apple Juice Concentrate', 280),
    ('Blueberry Juice', 241),
    ('Key Lime Juice', 227),
    ('Lemon Juice', 224),
    ('Vanilla Extract', 224),
    ('Almond Extract', 224),
    ('Peppermint Extract', 224),
    ('Food Coloring', 240),
    // --- Spices & Salts ---
    ('Salt (table)', 288),
    ('Salt (Kosher, Diamond Crystal)', 128),
    ("Salt (Kosher, Morton's)", 256),
    ('Cinnamon (ground)', 125),
    ('Espresso Powder', 112),
    ('Matcha Powder', 96),
    // --- Sourdough ---
    ('Sourdough Starter', 234),
    ('Gluten-Free Sourdough Starter', 205),
    // --- Pantry ---
    ('Breadcrumbs (dried)', 112),
    ('Breadcrumbs (fresh)', 84),
    ('Breadcrumbs (panko)', 50),
    ('Graham Cracker Crumbs', 100),
    ('Cookie Crumbs', 85),
    ('Granola', 113),
    ('Rice Krispies', 28),
    ('Grape Nuts', 114),
    ('Malted Milk Powder', 140),
    ('Meringue Powder', 172),
    ('Caramel Bits', 156),
    ('Toffee Chunks', 156),
    ('Instant Yeast', 144),
    ('Vital Wheat Gluten', 144),
    ('Non-Diastatic Malt Powder', 144),
    ('Lemon Juice Powder', 144),
    ('Sundried Tomatoes', 170),
    ('Shredded Coconut (sweetened)', 85),
    ('Shredded Coconut (unsweetened)', 53),
    ('Desiccated Coconut', 85),
    ('Coconut Flakes', 60),
    ('Marble/Caramel pieces', 284),
    // --- Decorations & Miscellaneous ---
    ('Sprinkles', 120),
    ('Nonpareils', 160),
    ('Pudding Mix', 170),
    ('Instant Pudding Mix', 170),
    ('Pudding (prepared)', 280),
  ];

  // MARK: Common ingredient priority
  //
  // Baking staples, ranked. The picker in AddEditRecipeView shows these
  // first — both when browsing the full list and as a tiebreaker among
  // several equally-relevant search matches (e.g. every "___ Flour"
  // variant scores the same for the query "flour") — so a baker isn't
  // hunting through 20 flour variants or 15 sugar variants for the one
  // they use in nearly every recipe.
  static final Map<String, int> commonPriority = () {
    const ranked = [
      'All-Purpose Flour', 'Granulated Sugar', 'Brown Sugar', 'Butter',
      'Egg', 'Milk', 'Baking Powder', 'Baking Soda', 'Salt (table)',
      'Vanilla Extract', 'Confectioners Sugar', 'Heavy Cream',
      'Cocoa Powder', 'Buttermilk', 'Sour Cream', 'Vegetable Oil',
      'Cream Cheese', 'Chocolate Chips',
    ];
    return {for (var i = 0; i < ranked.length; i++) ranked[i]: i};
  }();
}
