-- Add cottage baker product category tags to the global tag registry
INSERT INTO public.baker_specialty_tags (name) VALUES
    ('Cake Pops'),
    ('Decorated Cookies'),
    ('Traybakes'),
    ('Shortbread'),
    ('Fudge'),
    ('Rocky Road'),
    ('Celebration Cakes'),
    ('Custom Cakes'),
    ('Drip Cakes'),
    ('Floral Cakes'),
    ('Naked Cakes'),
    ('Number Cakes'),
    ('Mini Cakes'),
    ('Smash Cakes'),
    ('Cake Jars'),
    ('Cake Pops'),
    ('Cake Balls'),
    ('Bento Cakes'),
    ('Eclairs'),
    ('Profiteroles'),
    ('Caneles'),
    ('Financiers'),
    ('Madeleines'),
    ('Baklava'),
    ('Churros'),
    ('Waffles'),
    ('Crepes'),
    ('Babka'),
    ('Stollen'),
    ('Panettone'),
    ('Hot Cross Buns'),
    ('Bagels'),
    ('Pretzels'),
    ('Granola'),
    ('Energy Balls'),
    ('Meringues'),
    ('Pavlova'),
    ('Eton Mess'),
    ('Swiss Roll'),
    ('Yule Log'),
    ('Rum Balls'),
    ('Truffles'),
    ('Petit Fours'),
    ('Wedding Favours'),
    ('Custom Orders'),
    ('Wholesale'),
    ('Farmers Market'),
    ('Online Orders'),
    ('Local Delivery'),
    ('Pickup Only')
ON CONFLICT (name) DO NOTHING;
