-- Re-pin search_path on claim_invoice — the 20260722000002 hardening pass
-- pinned it (and claim_and_pay_invoice) via ALTER FUNCTION, but ALTER
-- FUNCTION ... SET does not survive a later CREATE OR REPLACE FUNCTION of
-- the same signature. claim_invoice was redefined since (most recently by
-- 20260807000004_disable_in_app_invoice_claim.sql) without re-specifying
-- the pin, silently regressing it back to a mutable search_path — the
-- exact class of vulnerability 20260722000002 fixed. SECURITY DEFINER
-- functions with a mutable search_path are vulnerable to search-path
-- hijacking by any role with schema-create privileges.
--
-- claim_and_pay_invoice itself no longer exists — it was DROPPED outright
-- by 20260805000004_drop_mock_claim_and_pay_invoice.sql (it never actually
-- called Stripe; replaced by claim_invoice + a real charge via
-- pay-invoice-order/finalize-invoice-payment), so there's nothing left to
-- re-pin there.
--
-- Any future CREATE OR REPLACE FUNCTION on a SECURITY DEFINER function must
-- re-specify `SET search_path = public` inline in the same statement — it
-- does not inherit from a prior ALTER FUNCTION call.

ALTER FUNCTION public.claim_invoice(text) SET search_path = public;
